### ISSUE TITLE
React 18에 대한 가이드를 Readme 문서에 포함해주세요~

### ISSUE THREAD

**Issue by koko8829** [soaple/first-met-react-practice#1]
4장 따라가다가 계속 오류가 나서 확인해보니 React 18에 대한 문제였는데 찾아보니 https://github.com/soaple/first-met-react-practice-v18 이 따로 있었네요. 

아마도 책을 따라서 진행하는 분들은 이곳 샘플을 참고할텐데~~ Readme 문서에 React 18 깃허브 링크를 안내해주시면 도움이 될 듯합니다.

**Comment by soaple** [comment]
안녕하세요, @koko8829님.
불편한 점을 제보해주셔서 감사합니다~
리액트 버전 18 실습 소스코드는 얼마 전에 만들어 뒀는데, 여기에는 따로 링크를 못 걸어두었네요.
방금 README에 관련 링크를 추가해두었습니다.
감사합니다!
